### ISSUE TITLE
好多歌播不了

### ISSUE THREAD

**Issue by ldgz321** [milkare/InnerMediaPlayer#1]
是黑胶会员，登陆了，但是很多歌播不了，reason是unknow

**Comment by milkare** [comment]
请把Player.log完整贴上来以便修改代码，因为我没有黑胶会员用来测试，所以可能对会员权限的判定有些错误。

**Comment by CyberHamburg** [comment]
> 是黑胶会员，登陆了，但是很多歌播不了，reason是unknow

请把Player.log完整贴上来以便修改代码，因为我没有黑胶会员用来测试，所以可能对会员权限的判定有些错误。

**Comment by CyberHamburg** [comment]
0.6.3v已修复

**Comment by ldgz123** [comment]
> 0.6.3v已修复

感谢感谢，我看地址能下到flac文件但是播不了，自己找了flac转mp3搞了下，不过得等下载好才能播不太行

**Comment by CyberHamburg** [comment]
> > 0.6.3v已修复
> 
> 感谢感谢，我看地址能下到flac文件但是播不了，自己找了flac转mp3搞了下，不过得等下载好才能播不太行

Unity对音频格式的支持不太好，后面我有打算用FFmpeg转码
